from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from reformers_model_api_server.models.base_model import Model
from reformers_model_api_server import util


class InfoCreateModelAdditionalProperties(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, info=None):  # noqa: E501
        """InfoCreateModelAdditionalProperties - a model defined in OpenAPI

        :param info: The info of this InfoCreateModelAdditionalProperties.  # noqa: E501
        :type info: str
        """
        self.openapi_types = {
            'info': str
        }

        self.attribute_map = {
            'info': 'info'
        }

        self._info = info

    @classmethod
    def from_dict(cls, dikt) -> 'InfoCreateModelAdditionalProperties':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The info_create_model_additionalProperties of this InfoCreateModelAdditionalProperties.  # noqa: E501
        :rtype: InfoCreateModelAdditionalProperties
        """
        return util.deserialize_model(dikt, cls)

    @property
    def info(self) -> str:
        """Gets the info of this InfoCreateModelAdditionalProperties.


        :return: The info of this InfoCreateModelAdditionalProperties.
        :rtype: str
        """
        return self._info

    @info.setter
    def info(self, info: str):
        """Sets the info of this InfoCreateModelAdditionalProperties.


        :param info: The info of this InfoCreateModelAdditionalProperties.
        :type info: str
        """

        self._info = info
