from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from reformers_model_api_server.models.base_model import Model
from reformers_model_api_server import util


class InfoAuth(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, _date=None):  # noqa: E501
        """InfoAuth - a model defined in OpenAPI

        :param _date: The _date of this InfoAuth.  # noqa: E501
        :type _date: str
        """
        self.openapi_types = {
            '_date': str
        }

        self.attribute_map = {
            '_date': 'date'
        }

        self.__date = _date

    @classmethod
    def from_dict(cls, dikt) -> 'InfoAuth':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The info_auth of this InfoAuth.  # noqa: E501
        :rtype: InfoAuth
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> str:
        """Gets the _date of this InfoAuth.

        timestamp of token authentication  # noqa: E501

        :return: The _date of this InfoAuth.
        :rtype: str
        """
        return self.__date

    @_date.setter
    def _date(self, _date: str):
        """Sets the _date of this InfoAuth.

        timestamp of token authentication  # noqa: E501

        :param _date: The _date of this InfoAuth.
        :type _date: str
        """

        self.__date = _date
