from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from reformers_model_api_server.models.base_model import Model
from reformers_model_api_server import util


class ModelParametersValue(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """ModelParametersValue - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ModelParametersValue':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The model_parameters_value of this ModelParametersValue.  # noqa: E501
        :rtype: ModelParametersValue
        """
        return util.deserialize_model(dikt, cls)
