from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from reformers_model_api_server.models.base_model import Model
from reformers_model_api_server import util


class ModelGeneratorParametersValueDefault(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """ModelGeneratorParametersValueDefault - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ModelGeneratorParametersValueDefault':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The model_generator_parameters_value_default of this ModelGeneratorParametersValueDefault.  # noqa: E501
        :rtype: ModelGeneratorParametersValueDefault
        """
        return util.deserialize_model(dikt, cls)
